Initial implementation of reload for haproxy

diff --git a/haproxy b/haproxy
--- a/haproxy
+++ b/haproxy
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 #
 # Resource script for haproxy daemon
 #
@@ -26,184 +26,182 @@
 ##########################################################################
 # Initialization:
 
-: ${OCF_FUNCTIONS_DIR=${OCF_ROOT}/resource.d/heartbeat}
-. ${OCF_FUNCTIONS_DIR}/.ocf-shellfuncs
+OCF_FUNCTIONS_DIR=/usr/lib/ocf/resource.d/heartbeat
+# shellcheck disable=SC1090
+source ${OCF_FUNCTIONS_DIR}/.ocf-shellfuncs
 
-USAGE="Usage: $0 {start|stop|status|monitor|validate-all|meta-data}";
+USAGE="Usage: $0 {start|stop|reload|status|monitor|validate-all|meta-data}";
 
 ##########################################################################
 
-usage()
-{
-	echo $USAGE >&2
+function usage() {
+  echo "${USAGE}" >&2
 }
 
-meta_data()
-{
-cat <<END
+function meta_data() {
+  cat <<END
 <?xml version="1.0"?>
 <!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
 <resource-agent name="haproxy">
-<version>1.0</version>
-<longdesc lang="en">
-This script manages haproxy daemon
-</longdesc>
-<shortdesc lang="en">Manages an haproxy daemon</shortdesc>
+  <version>1.0</version>
+  <longdesc lang="en">
+    This script manages haproxy daemon
+  </longdesc>
+  <shortdesc lang="en">Manages an haproxy daemon</shortdesc>
 
-<parameters>
+  <parameters>
 
-<parameter name="binpath">
-<longdesc lang="en">
-The haproxy binary path.
-For example, "/usr/sbin/haproxy"
-</longdesc>
-<shortdesc lang="en">Full path to the haproxy binary</shortdesc>
-<content type="string" default="/usr/sbin/haproxy"/>
-</parameter>
+    <parameter name="binpath">
+      <longdesc lang="en">
+        The haproxy binary path.
+        For example, "/usr/sbin/haproxy"
+      </longdesc>
+      <shortdesc lang="en">Full path to the haproxy binary</shortdesc>
+      <content type="string" default="/usr/sbin/haproxy"/>
+    </parameter>
 
-<parameter name="conffile">
-<longdesc lang="en">
-The haproxy daemon configuration file name with full path.
-For example, "/etc/haproxy/haproxy.cfg"
-</longdesc>
-<shortdesc lang="en">Configuration file name with full path</shortdesc>
-<content type="string" default="/etc/haproxy/haproxy.cfg" />
-</parameter>
+    <parameter name="conffile">
+      <longdesc lang="en">
+        The haproxy daemon configuration file name with full path.
+        For example, "/etc/haproxy/haproxy.cfg"
+      </longdesc>
+      <shortdesc lang="en">Configuration file name with full path</shortdesc>
+      <content type="string" default="/etc/haproxy/haproxy.cfg" />
+    </parameter>
 
-<parameter name="extraconf">
-<longdesc lang="en">
-Extra command line arguments to pass to haproxy.
-For example, "-f /etc/haproxy/shared.cfg"
-</longdesc>
-<shortdesc lang="en">Extra command line arguments for haproxy</shortdesc>
-<content type="string" default="" />
-</parameter>
+    <parameter name="extraconf">
+      <longdesc lang="en">
+        Extra command line arguments to pass to haproxy.
+        For example, "-f /etc/haproxy/shared.cfg"
+      </longdesc>
+      <shortdesc lang="en">Extra command line arguments for haproxy</shortdesc>
+      <content type="string" default="" />
+    </parameter>
 
-</parameters>
+  </parameters>
 
-<actions>
-<action name="start" timeout="20s"/>
-<action name="stop" timeout="20s"/>
-<action name="monitor" depth="0" timeout="20s" interval="60s" />
-<action name="validate-all" timeout="20s"/>
-<action name="meta-data"  timeout="5s"/>
-</actions>
+  <actions>
+    <action name="start" timeout="20s"/>
+    <action name="stop" timeout="20s"/>
+    <action name="reload" timeout="20s"/>
+    <action name="monitor" depth="0" timeout="20s" interval="60s" />
+    <action name="validate-all" timeout="20s"/>
+    <action name="meta-data"  timeout="5s"/>
+  </actions>
 </resource-agent>
 END
-exit $OCF_SUCCESS
+  exit "${OCF_SUCCESS}"
 }
 
-get_pid_and_conf_file()
-{
-	if [ -n "$OCF_RESKEY_conffile" ]; then
-		CONF_FILE=$OCF_RESKEY_conffile
-	else
-		CONF_FILE="/etc/haproxy/haproxy.cfg"
-	fi
+function get_pid_and_conf_file() {
+  CONF_FILE="${OCF_RESKEY_conffile-/etc/haproxy/haproxy.cfg}"
 
-	PIDFILE="`grep -v \"#\" ${CONF_FILE} | grep \"pidfile\" | sed 's/^[ \t]*pidfile[ \t]*//'`"
-	if [ "${PIDFILE}" = '' ]; then
-		PIDFILE="/var/run/${OCF_RESOURCE_INSTANCE}.pid"
-	fi
+  PIDFILE=$(grep 'pidfile' "${CONF_FILE}" | sed -e '/^#/ d' -e 's/^\s*pidfile\s*//')
+  if [[ -z $PIDFILE ]]; then
+    PIDFILE="/var/run/${OCF_RESOURCE_INSTANCE}.pid"
+  fi
 }
 
-haproxy_status()
-{
-	if [ -n "$PIDFILE" -a -f "$PIDFILE" ]; then
-		# haproxy is probably running
-		PID=`cat $PIDFILE`
-		if [ -n "$PID" ]; then
-			if ps -p $PID | grep haproxy >/dev/null ; then
-				ocf_log info "haproxy daemon running"
-				return $OCF_SUCCESS
-			else
-				ocf_log info "haproxy daemon is not running but pid file exists"
-				return $OCF_NOT_RUNNING
-			fi
-		else
-			ocf_log err "PID file empty!"
-			return $OCF_ERR_GENERIC
-		fi
-	fi
+function haproxy_status() {
+  if [[ -n $PIDFILE && -f $PIDFILE ]]; then
+    # haproxy is probably running
+    PID=$(cat "${PIDFILE}")
+    if [[ -n $PID ]]; then
+      # shellcheck disable=SC2009
+      if ps -fp "${PID}" | grep haproxy | grep "${CONF_FILE}" >/dev/null ; then
+        ocf_log info "haproxy daemon running"
+        return "${OCF_SUCCESS}"
+      else
+        ocf_log info "haproxy daemon is not running but pid file exists"
+        return "${OCF_NOT_RUNNING}"
+      fi
+    else
+      ocf_log err "PID file empty!"
+      return "${OCF_ERR_GENERIC}"
+    fi
+  fi
 
-	# haproxy is not running
-	ocf_log info "haproxy daemon is not running"
-	return $OCF_NOT_RUNNING
+  # haproxy is not running
+  ocf_log info "haproxy daemon is not running"
+  return "${OCF_NOT_RUNNING}"
 }
 
-haproxy_start()
-{
-	# if haproxy is running return success
-	haproxy_status
-	retVal=$?
-	if [ $retVal -eq $OCF_SUCCESS ]; then
-		exit $OCF_SUCCESS
-	elif [ $retVal -ne $OCF_NOT_RUNNING ]; then
-		ocf_log err "Error. Unknown status."
-		exit $OCF_ERR_GENERIC
-	fi
+function haproxy_start() {
+  # if haproxy is running return success
+  haproxy_status
+  retval=$?
+  if [[ $retval -eq $OCF_SUCCESS ]]; then
+    exit "${OCF_SUCCESS}"
+  elif [[ $retval -ne $OCF_NOT_RUNNING ]]; then
+    ocf_log err "Error. Unknown status."
+    exit "${OCF_ERR_GENERIC}"
+  fi
 
-	if [ -n "$OCF_RESKEY_binpath" ]; then
-		COMMAND="$OCF_RESKEY_binpath"
-	else
-		COMMAND="/usr/sbin/haproxy"
-	fi
+  COMMAND="${OCF_RESKEY_binpath-/usr/sbin/haproxy}"
 
-	$COMMAND $OCF_RESKEY_extraconf -f $CONF_FILE -p $PIDFILE;
-	if [ $? -ne 0 ]; then
-		ocf_log err "Error. haproxy daemon returned error $?."
-		exit $OCF_ERR_GENERIC
-	fi
+  if ! $COMMAND "${OCF_RESKEY_extraconf-}" -f "${CONF_FILE}" -p "${PIDFILE}"; then
+    ocf_log err "Error. haproxy daemon returned error $?."
+    exit "${OCF_ERR_GENERIC}"
+  fi
 
-	ocf_log info "Started haproxy daemon."
-	exit $OCF_SUCCESS
+  ocf_log info "Started haproxy daemon."
+  exit "${OCF_SUCCESS}"
 }
 
-
-haproxy_stop()
-{
-	if haproxy_status ; then
-		PID=`cat $PIDFILE`
-		if [ -n "$PID" ] ; then
-			kill $PID
-			if [ $? -ne 0 ]; then
-				kill -SIGKILL $PID
-				if [ $? -ne 0 ]; then
-					ocf_log err "Error. Could not stop haproxy daemon."
-					return $OCF_ERR_GENERIC
-				fi
-			fi
-			rm $PIDFILE 2>/dev/null
-		fi
-	fi
-	ocf_log info "Stopped haproxy daemon."
-	exit $OCF_SUCCESS
+function haproxy_stop() {
+  if haproxy_status; then
+    if [[ -n $PID ]]; then
+      if ! kill "${PID}"; then
+        if ! kill -SIGKILL "${PID}"; then
+          ocf_log err "Error. Could not stop haproxy daemon."
+          return "${OCF_ERR_GENERIC}"
+        fi
+      fi
+      rm "${PIDFILE}" 2>/dev/null
+    fi
+  fi
+  ocf_log info "Stopped haproxy daemon."
+  exit "${OCF_SUCCESS}"
 }
 
-haproxy_monitor()
-{
-	haproxy_status
+function haproxy_reload() {
+  # if haproxy is not running return error
+  if ! haproxy_status; then
+    ocf_log err "Error. haproxy daemon is not running."
+    exit "${OCF_ERR_GENERIC}"
+  fi
+
+  COMMAND="${OCF_RESKEY_binpath-/usr/sbin/haproxy}"
+
+  if ! $COMMAND "${OCF_RESKEY_extraconf-}" -f "${CONF_FILE}" -p "${PIDFILE}" -sf "${PIDFILE}"; then
+    ocf_log err "Error. haproxy daemon returned error $?."
+    exit "${OCF_ERR_GENERIC}"
+  fi
+
+  ocf_log info "Reloaded haproxy daemon."
+  exit "${OCF_SUCCESS}"
 }
 
-haproxy_validate_all()
-{
-	if [ -n "$OCF_RESKEY_binpath" -a ! -x "$OCF_RESKEY_binpath" ]; then
-		ocf_log err "Binary path $OCF_RESKEY_binpath does not exist."
-		exit $OCF_ERR_ARGS
-	fi
-	if [ -n "$OCF_RESKEY_conffile" -a ! -f "$OCF_RESKEY_conffile" ]; then
-		ocf_log err "Config file $OCF_RESKEY_conffile does not exist."
-		exit $OCF_ERR_ARGS
-	fi
+function haproxy_monitor() {
+  haproxy_status
+}
 
-	if  grep -v "^#" "$CONF_FILE" | grep "pidfile" > /dev/null ; then
-		:
-	else
-		ocf_log err "Error. \"pidfile\" entry required in the haproxy config file by haproxy OCF RA."
-		return $OCF_ERR_GENERIC
-	fi
+function haproxy_validate_all() {
+  if [[ -n $OCF_RESKEY_binpath && ! -x $OCF_RESKEY_binpath ]]; then
+    ocf_log err "Binary path $OCF_RESKEY_binpath does not exist."
+    exit "${OCF_ERR_ARGS}"
+  fi
+  if [[ -n $OCF_RESKEY_conffile && ! -f $OCF_RESKEY_conffile ]]; then
+    ocf_log err "Config file $OCF_RESKEY_conffile does not exist."
+    exit "${OCF_ERR_ARGS}"
+  fi
 
-	return $OCF_SUCCESS
+  if ! grep -v "^#" "$CONF_FILE" | grep "pidfile" > /dev/null ; then
+    ocf_log err "Error. \"pidfile\" entry required in the haproxy config file by haproxy OCF RA."
+    return "${OCF_ERR_GENERIC}"
+  fi
+
+  return "${OCF_SUCCESS}"
 }
 
 
@@ -212,39 +210,44 @@ haproxy_validate_all()
 #
 
 if [ $# -ne 1 ]; then
-	usage
-	exit $OCF_ERR_ARGS
+  usage
+  exit "${OCF_ERR_ARGS}"
 fi
 
 case $1 in
-	start)	get_pid_and_conf_file
-		haproxy_start
-		;;
-
-	stop)	get_pid_and_conf_file
-		haproxy_stop
-		;;
-
-	status)	get_pid_and_conf_file
-		haproxy_status
-		;;
-
-	monitor)get_pid_and_conf_file
-		haproxy_monitor
-		;;
-
-	validate-all)	get_pid_and_conf_file
-			haproxy_validate_all
-			;;
-
-	meta-data)	meta_data
-			;;
-
-	usage)	usage
-		exit $OCF_SUCCESS
-		;;
-
-	*)	usage
-		exit $OCF_ERR_UNIMPLEMENTED
-		;;
+  'start')
+    get_pid_and_conf_file
+    haproxy_start
+    ;;
+  'stop')
+    get_pid_and_conf_file
+    haproxy_stop
+    ;;
+  'reload')
+    get_pid_and_conf_file
+    haproxy_reload
+    ;;
+  'status')
+    get_pid_and_conf_file
+    haproxy_status
+    ;;
+  'monitor')
+    get_pid_and_conf_file
+    haproxy_monitor
+    ;;
+  'validate'-all)
+    get_pid_and_conf_file
+    haproxy_validate_all
+    ;;
+  'meta-data')
+    meta_data
+    ;;
+  'usage')
+    usage
+    exit "${OCF_SUCCESS}"
+    ;;
+  *)
+    usage
+    exit "${OCF_ERR_UNIMPLEMENTED}"
+    ;;
 esac
